<?php
require_once '../bdd/Database.php';
class Etudiant extends Utilisateur
{
    private $ref_utilisateur;
    private $domaine;
    private $bdd;


    public function __construct(array $donnees){
        $this->hydrate($donnees);
        $this->bdd = new Database();
    }

    public function hydrate(array $donnees){
        foreach ($donnees as $key => $value)
        {
            $method = 'set'.ucfirst($key);

            if (method_exists($this, $method))
            {
                $this->$method($value);
            }
        }
    }



    public function selectUtilisateur()
    {
        return parent::selectUtilisateur(); // TODO: Change the autogenerated stub
    }

    public function addUtilisateur()
    {
        parent::addUtilisateur(); // TODO: Change the autogenerated stub
    }


    public function updateUtilisateur()
    {
        parent::updateUtilisateur(); // TODO: Change the autogenerated stub
    }

    public function deleteUtilisateur()
    {
        parent::deleteUtilisateur(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getRefUtilisateur()
    {
        return $this->ref_utilisateur;
    }

    /**
     * @param mixed $ref_utilisateur
     */
    public function setRefUtilisateur($ref_utilisateur)
    {
        $this->ref_utilisateur = $ref_utilisateur;
    }

    /**
     * @return mixed
     */
    public function getDomaine()
    {
        return $this->domaine;
    }

    /**
     * @param mixed $domaine
     */
    public function setDomaine($domaine)
    {
        $this->domaine = $domaine;
    }




}